dependencies:
- name: cloud-native-poc-email
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: cloud-native-poc-kafka
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
- name: cloud-native-poc-kafka-email-consumer
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: cloud-native-poc-kafka-exporter
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: cloud-native-poc-kafka-pdf-consumer
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: cloud-native-poc-mysql
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: cloud-native-poc-mysql2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.13
- name: cloud-native-poc-pdf
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.25
- name: cloud-native-poc-vault
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: cloud-native-poc-zookeeper
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.32
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: jm15
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
