dependencies:
- name: cloud-native-poc-email
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: cloud-native-poc-pdf
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.22
- name: cloud-native-poc-zookeeper
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.27
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: jm15
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
